modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="nimble"
version="${file.jarVersion}"
displayName="Nimble"
authors="Snownee, liach"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nimble"
description=""
